name: mdsdap
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost-cpp=1.74.0=h75c5d50_8
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py39h06a4308_0
  - comm=0.1.2=py39h06a4308_0
  - cryptography=41.0.3=py39hdda0065_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dnspython=2.2.1=py39h06a4308_0
  - dominate=2.8.0=pyhd8ed1ab_0
  - email-validator=1.2.1=py39h06a4308_0
  - exceptiongroup=1.0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - flask-bootstrap=3.3.7.1=py_0
  - flask-wtf=1.0.1=py39h06a4308_0
  - icu=70.1=h27087fc_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.0.0=py39h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.25.0=py39h2f386ee_0
  - ipython=8.15.0=py39h06a4308_0
  - jedi=0.18.1=py39h06a4308_1
  - jsonschema=4.19.2=py39h06a4308_0
  - jsonschema-specifications=2023.7.1=py39h06a4308_0
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_core=5.5.0=py39h06a4308_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=8.4.0=h251f7ec_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mongodb=6.0.0=h0e13805_0
  - nbformat=5.9.2=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.26.0=py39h5f9d8c6_0
  - numpy-base=1.26.0=py39hb5e798b_0
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.1=py39h06a4308_0
  - pandas=2.1.1=py39h1128e8f_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3=py39h06a4308_0
  - platformdirs=3.10.0=py39h06a4308_0
  - plotly=3.10.0=py_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39h06a4308_1
  - pymongo=3.12.0=py39h295c915_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py39h06a4308_0
  - pyzmq=25.1.0=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py39h06a4308_0
  - requests=2.31.0=py39h06a4308_0
  - retrying=1.3.3=pyhd3eb1b0_2
  - rpds-py=0.10.6=py39hb02cf49_0
  - setuptools=68.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.2=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py39h5eee18b_0
  - tqdm=4.65.0=py39hb070fc8_0
  - traitlets=5.7.1=py39h06a4308_0
  - typing_extensions=4.7.1=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.18=py39h06a4308_0
  - visitor=0.1.3=pyh9f0ad1d_1
  - wheel=0.41.2=py39h06a4308_0
  - wtforms=2.3.3=pyhd3eb1b0_0
  - xz=5.4.2=h5eee18b_0
  - yaml-cpp=0.7.0=h295c915_1
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
    - blinker==1.7.0
    - dukpy==0.3.0
    - flask==3.0.0
    - flask-ckeditor==0.5.0
    - flask-dropzone==1.6.0
    - flask-login==0.6.3
    - flask-sqlalchemy==3.1.1
    - future==0.18.3
    - greenlet==3.0.1
    - itsdangerous==2.1.2
    - javascripthon==0.12
    - jinja2==3.0.0
    - jupyter-echarts-pypkg==0.1.1
    - lml==0.0.2
    - pillow==10.1.0
    - prettytable==3.9.0
    - pubchempy==1.0.4
    - pyecharts==0.5.0
    - pyecharts-javascripthon==0.0.6
    - pyecharts-jupyter-installer==0.0.3
    - python-dotenv==1.0.0
    - simplejson==3.19.2
    - sqlalchemy==2.0.23
    - typing-extensions==4.8.0
    - wcwidth==0.2.10
    - werkzeug==2.2.2
prefix: /home/liwh/.conda/envs/mdsdap
